import "./global.css";
import Navbar from "../components/navbar/navbar";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>
        <Navbar />
        <main>
        {children}
        </main>
      </body>
    </html>
  )
}
